name: nutty_putty_avatars
description: Package for adding avatars to any application.
version: 0.0.1
author: LinkUp Studio<info@linkupst.com>
homepage: https://github.com/nuttyputty/nutty_putty_avatars.git

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hsvcolor_picker: ^0.0.1
  flutter_svg: ^0.15.0
  flutter_inapp_purchase: ^2.0.4
  
  flutter_circle_color_picker: ^0.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/ListBg.png
    - assets/images/person/
    - assets/images/heads/
    - assets/images/partIcons/
    - assets/images/mouth/
    - assets/images/hairs/
    - assets/images/faceHair/
    - assets/images/eyes/
  

 